---
- name: Instalando apache
  apt: name=apache2 state=present

- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present


- name: Crear la carpeta del sitio
  file: path=/var/www/html/ state=directory
  
  notify:
     -name: reiniciando apache
