---


- include: install.yml
  tags:
    - networking
    - vsftpd
    - install
    - vsftpd-install

- include: config.yml
  tags:
    - networking
    - vsftpd
    - config
    - vsftpd-config

- include: manage.yml
  tags:
    - networking
    - vsftpd
    - manage
    - vsftpd-manage

- include: service.yml
  tags:
    - networking
    - vsftpd
    - service
    - vsftpd-service
