- name: Instalando curl
  apt: name=curl state=present

- name: Downloading nodejs
  command: sh scripts/curl.sh

- name: Installing nodejs
  apt: name=nodejs state=present

- name: Installing npm
  apt: name=npm state=present
